/**
 * Ridah Intro Sequence - Cinematic typewriter intro with breathe moment
 */

export type RidahStepStyle = "normal" | "dim" | "arabic" | "emphasis";

export interface RidahStep {
  id: string;
  type: "type" | "breathe" | "end";
  text?: string;
  speedMs?: number; // Optional; default uses global (34ms)
  varianceMs?: number; // Optional; default uses global (18ms)
  pauseAfterMs?: number;
  style?: RidahStepStyle;
  act: number; // Act number for grouping
  actTitle?: string; // Optional title for first step of each act
  actEnd?: boolean; // True if this is the last line of an act
}

// Global defaults
const GLOBAL_SPEED_MS = 34;
const GLOBAL_VARIANCE_MS = 18;

export const RIDAH_INTRO_SEQUENCE: RidahStep[] = [
  // ACT 1: Opening
  {
    id: "step-1",
    type: "type",
    text: "curious soul!",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 1,
    actTitle: "I",
  },
  {
    id: "step-2",
    type: "type",
    text: "happy you made it here 😊",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 950,
    style: "normal",
    act: 1,
  },
  {
    id: "step-3",
    type: "type",
    text: "in our busy lives, we seldom pause to just be.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 1,
  },
  {
    id: "step-4",
    type: "type",
    text: "ridah... ever heard of it?",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1300,
    style: "normal",
    act: 1,
  },
  {
    id: "step-5",
    type: "type",
    text: "thank goodness for google, right?",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1050,
    style: "normal",
    act: 1,
  },
  {
    id: "step-6",
    type: "type",
    text: "رضا.",
    speedMs: 52,
    varianceMs: 22,
    pauseAfterMs: 1300,
    style: "arabic",
    act: 1,
  },
  {
    id: "step-7",
    type: "type",
    text: "an arabic word for",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 850,
    style: "normal",
    act: 1,
  },
  {
    id: "step-8",
    type: "type",
    text: "contentment.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 1,
    actEnd: true,
  },
  
  // ACT 2: Personal Journey
  {
    id: "step-9",
    type: "type",
    text: "i've been exploring it for over 12 years now.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 2,
    actTitle: "II",
  },
  {
    id: "step-10",
    type: "type",
    text: "yes... i'm 18 😅",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1300,
    style: "normal",
    act: 2,
  },
  {
    id: "step-11",
    type: "type",
    text: "happiness? what even is that?",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 2,
  },
  {
    id: "step-12",
    type: "type",
    text: "there are theories. philosophies. entire books written about it.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1250,
    style: "normal",
    act: 2,
  },
  {
    id: "step-13",
    type: "type",
    text: "i've seen it all.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 950,
    style: "normal",
    act: 2,
  },
  {
    id: "step-14",
    type: "type",
    text: "the more you experience, the more you think you know.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1050,
    style: "normal",
    act: 2,
  },
  {
    id: "step-15",
    type: "type",
    text: "but actually... the more you realize you don't...",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1500,
    style: "normal",
    act: 2,
  },
  {
    id: "step-16",
    type: "type",
    text: "and that's exactly where you understand one thing.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 2,
  },
  {
    id: "step-17",
    type: "type",
    text: "ridah.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 2,
  },
  {
    id: "step-18",
    type: "type",
    text: "voilà!!",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 2,
    actEnd: true,
  },
  
  // ACT 3: Philosophy
  {
    id: "step-19",
    type: "type",
    text: "so what if we don't know what happiness is?",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 3,
    actTitle: "III",
  },
  {
    id: "step-20",
    type: "type",
    text: "we don't know what a lot of things are.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1000,
    style: "normal",
    act: 3,
  },
  {
    id: "step-21",
    type: "type",
    text: "but one thing we do know:",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 800,
    style: "normal",
    act: 3,
  },
  {
    id: "step-22",
    type: "type",
    text: "to enjoy it.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 3,
  },
  {
    id: "step-23",
    type: "type",
    text: "to smile when we hold a door, and then throw it open for the next person.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 3,
  },
  {
    id: "step-24",
    type: "type",
    text: "when we offer a spot in a crowded bus, or let someone merge in traffic.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 3,
  },
  {
    id: "step-25",
    type: "type",
    text: "when we're making the world...",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 700,
    style: "normal",
    act: 3,
  },
  {
    id: "step-26",
    type: "type",
    text: "simply",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 650,
    style: "normal",
    act: 3,
  },
  {
    id: "step-27",
    type: "type",
    text: "better.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1400,
    style: "normal",
    act: 3,
    actEnd: true,
  },
  
  // ACT 4: Present Moment
  {
    id: "step-28",
    type: "type",
    text: "right now you're reading words on a screen…",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 4,
    actTitle: "IV",
  },
  {
    id: "step-29",
    type: "type",
    text: "you can't look away at the tree outside your window.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 4,
  },
  {
    id: "step-30",
    type: "type",
    text: "but when you do have a moment, look at one.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 4,
  },
  {
    id: "step-31",
    type: "type",
    text: "we have plenty... i promise.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 4,
    actEnd: true,
  },
  
  // ACT 5: Personal Connection (renumbered from ACT 6)
  {
    id: "step-38",
    type: "type",
    text: "you, reading this right now.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 850,
    style: "normal",
    act: 5,
    actTitle: "V",
  },
  {
    id: "step-39",
    type: "type",
    text: "i appreciate you as you are 😇",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 5,
  },
  {
    id: "step-40",
    type: "type",
    text: "for who you are.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 5,
  },
  
  // ACT 6: Final Thoughts (renumbered from ACT 7)
  {
    id: "step-42",
    type: "type",
    text: "curious soul... here is me, plated on a website…",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1200,
    style: "normal",
    act: 6,
    actTitle: "VI",
  },
  {
    id: "step-43",
    type: "type",
    text: "as ridiculous as it sounds, it's my way of expressing:",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 900,
    style: "normal",
    act: 7,
  },
  {
    id: "step-44",
    type: "type",
    text: "humane professionalism.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 850,
    style: "normal",
    act: 6,
  },
  {
    id: "step-45",
    type: "type",
    text: "thoughtful vulnerability.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 6,
  },
  {
    id: "step-46",
    type: "type",
    text: "everyone has their own terms as we said",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1300,
    style: "normal",
    act: 6,
  },
  {
    id: "step-47",
    type: "type",
    text: "here you go.",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 800,
    style: "normal",
    act: 6,
  },
  
  {
    id: "step-49",
    type: "type",
    text: "remember... ridah comes first, and lasts forever",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1100,
    style: "normal",
    act: 6,
  },
  {
    id: "step-50",
    type: "type",
    text: "enjoy",
    speedMs: GLOBAL_SPEED_MS,
    varianceMs: GLOBAL_VARIANCE_MS,
    pauseAfterMs: 1600,
    style: "normal",
    act: 6,
    actEnd: true,
  },
  
  // Final breathe gate (after all text)
  {
    id: "breathe-final",
    type: "breathe",
    act: 99,
  },
  
  // End
  {
    id: "end",
    type: "end",
    act: 99,
  },
];
